@startuml
!pragma layout smetana

!include diagram.styles.puml

autonumber

box "Consumer (Prover) Entity"
participant "Resource Owner (Client 1)" as C
participant "Secure Token Service" as STS
participant "Credential Service" as CS
end box

box "Provider (Verifier) Entity"
participant "Client 2 (Verifier)" as V
end box

C -> STS: SI token request (provide: Provider DID)
STS -> C: Token response w/ access token\n(bound to Provider DID)\n

C-> V: Request w/ si token and access token
V-> CS: request w/ access token
CS ->V: VP response
@enduml
